// Ready-made library voices. They are the engine's built-in default voices (generic stock voices, not real people),
// usable through the public API as voice_id "jsf_default_<id>". Hide any of them from Admin → Voices.
const RAW = [
  ["woodrow", "Woodrow", 'M', 'en-US'],
  ["victoria", "Victoria", 'F', 'en-US'],
  ["tonya", "Tonya", 'F', 'en-US'],
  ["todd", "Todd", 'M', 'en-US'],
  ["tasha", "Tasha", 'F', 'en-US'],
  ["susan", "Susan", 'F', 'en-US'],
  ["stacy", "Stacy", 'F', 'en-US'],
  ["sabrina", "Sabrina", 'F', 'en-US'],
  ["ruby", "Ruby", 'F', 'en-US'],
  ["robbie", "Robbie", 'F', 'en-US'],
  ["rob", "Rob", 'M', 'en-US'],
  ["richard", "Richard", 'M', 'en-US'],
  ["regina", "Regina", 'F', 'en-US'],
  ["reba", "Reba", 'F', 'en-US'],
  ["oliver", "Oliver", 'M', 'en-US'],
  ["nikki", "Nikki", 'F', 'en-US'],
  ["nick", "Nick", 'M', 'en-US'],
  ["monica", "Monica", 'F', 'en-US'],
  ["mildred", "Mildred", 'F', 'en-US'],
  ["megan", "Megan", 'F', 'en-US'],
  ["mason", "Mason", 'M', 'en-US'],
  ["mark", "Mark", 'M', 'en-US'],
  ["marcus", "Marcus", 'M', 'en-US'],
  ["marco", "Marco", 'M', 'en-US'],
  ["lyle", "Lyle", 'M', 'en-US'],
  ["lyla", "Lyla", 'F', 'en-US'],
  ["lowell", "Lowell", 'M', 'en-US'],
  ["lisa", "Lisa", 'F', 'en-US'],
  ["lindy", "Lindy", 'F', 'en-US'],
  ["lexi", "Lexi", 'F', 'en-US'],
  ["leah", "Leah", 'F', 'en-US'],
  ["kristy", "Kristy", 'F', 'en-US'],
  ["kristin", "Kristin", 'F', 'en-US'],
  ["ken", "Keenan", 'M', 'en-US'],
  ["kayla", "Kayla", 'F', 'en-US'],
  ["kara", "Kara", 'F', 'en-US'],
  ["julie", "Julie", 'F', 'en-US'],
  ["jordan", "Jordan", 'M', 'en-US'],
  ["joe", "Joe", 'M', 'en-US'],
  ["jesse", "Jesse", 'M', 'en-US'],
  ["jennifer", "Jennifer", 'F', 'en-US'],
  ["jean", "Jean", 'F', 'en-US'],
  ["janelle", "Janelle", 'F', 'en-US'],
  ["james", "James", 'M', 'en-US'],
  ["jacob", "Jacob", 'M', 'en-US'],
  ["jack", "Jack", 'M', 'en-US'],
  ["henry", "Henry", 'M', 'en-US'],
  ["zubair", "Zubair", 'M', 'ur-PK'],
  ["zeeshan", "Zeeshan", 'M', 'ur-PK'],
  ["zainab", "Zainab", 'F', 'ur-PK'],
  ["yasir", "Yasir", 'M', 'ur-PK'],
  ["waleed", "Waleed", 'M', 'ur-PK'],
  ["usman", "Usman", 'M', 'ur-PK'],
  ["tehmina", "Tehmina", 'F', 'ur-PK'],
  ["tasneem", "Tasneem", 'F', 'ur-PK'],
  ["vyom", "Vyom", 'M', 'hi-IN'],
  ["varun", "Varun", 'M', 'hi-IN'],
  ["tanvi", "Tanvi", 'F', 'hi-IN'],
  ["swati", "Swati", 'F', 'hi-IN'],
  ["suresh", "Suresh", 'M', 'hi-IN'],
  ["suraj", "Suraj", 'M', 'hi-IN'],
  ["suman", "Suman", 'F', 'hi-IN'],
  ["sanya", "Sanya", 'F', 'hi-IN'],
  ["yamileth", "Yamileth", 'F', 'es-ES'],
  ["valeria", "Valeria", 'F', 'es-ES'],
  ["romina", "Romina", 'F', 'es-ES'],
  ["rafael", "Rafael", 'M', 'es-ES'],
  ["miguel-angel", "Miguel Ángel", 'M', 'es-ES'],
  ["maximiliano", "Maximiliano", 'M', 'es-ES'],
  ["matias", "Matías", 'M', 'es-ES'],
  ["mariana", "Mariana", 'F', 'es-ES'],
  ["zeynep", "Zeynep", 'F', 'tr-TR'],
  ["yusuf", "Yusuf", 'M', 'tr-TR'],
  ["yasemin", "Yasemin", 'F', 'tr-TR'],
  ["ugur", "Uğur", 'M', 'tr-TR'],
  ["sinan", "Sinan", 'M', 'tr-TR'],
  ["sibel", "Sibel", 'F', 'tr-TR'],
  ["sevgi", "Sevgi", 'F', 'tr-TR'],
  ["serkan", "Serkan", 'M', 'tr-TR'],
  ["zoya", "Zoya", 'F', 'ru-RU'],
  ["yulia", "Yulia", 'F', 'ru-RU'],
  ["xenia", "Xenia", 'F', 'ru-RU'],
  ["vyacheslav", "Vyacheslav", 'M', 'ru-RU'],
  ["vladislav", "Vladislav", 'M', 'ru-RU'],
  ["violetta", "Violetta", 'F', 'ru-RU'],
  ["valery", "Valery", 'M', 'ru-RU'],
  ["ulyana", "Ulyana", 'F', 'ru-RU'],
  ["yoon-jung", "Yoon-jung", 'F', 'ko-KR'],
  ["yoo-jin", "Yoo-jin", 'F', 'ko-KR'],
  ["yeon-woo", "Yeon-woo", 'F', 'ko-KR'],
  ["woo-jin", "Woo-jin", 'M', 'ko-KR'],
  ["tae-hyun", "Tae-hyun", 'M', 'ko-KR'],
  ["sung-hoon", "Sung-hoon", 'M', 'ko-KR'],
  ["sun-hee", "Sun-hee", 'F', 'ko-KR'],
  ["soo-min", "Soo-min", 'F', 'ko-KR'],
  ["yan-ting", "Yan-Ting", 'F', 'zh-HK'],
  ["wing-hong", "Wing-Hong", 'M', 'zh-HK'],
  ["wai-kin", "Wai-Kin", 'M', 'zh-HK'],
  ["tak-wah", "Tak-Wah", 'M', 'zh-HK'],
  ["kin-fung", "Kin-Fung", 'M', 'zh-HK'],
  ["ka-yan", "Ka-Yan", 'F', 'zh-HK'],
  ["hiu-ching", "Hiu-Ching", 'F', 'zh-HK'],
  ["chun-wah", "Chun-Wah", 'M', 'zh-HK'],
  ["moshe", "Moshe", 'M', 'he-IL'],
  ["lital", "Lital", 'F', 'he-IL'],
  ["inbar", "Inbar", 'F', 'he-IL'],
  ["gil", "Gil", 'M', 'he-IL'],
];

const PREVIEW_TEXT = {
  en: "Hi, I'm {name}. I can narrate your videos, ads, courses and stories in a natural, studio-quality voice.",
  ur: "السلام علیکم، میں {name} ہوں۔ میں آپ کی ویڈیوز، اشتہارات اور کہانیوں کے لیے قدرتی آواز میں وائس اوور کر سکتا ہوں۔",
  hi: "नमस्ते, मैं {name} हूँ। मैं आपके वीडियो, विज्ञापन और कहानियों के लिए स्वाभाविक आवाज़ में वॉइसओवर कर सकता हूँ।",
  es: "Hola, soy {name}. Puedo narrar tus videos, anuncios, cursos e historias con una voz natural de estudio.",
  tr: "Merhaba, ben {name}. Videolarınızı, reklamlarınızı ve hikayelerinizi doğal bir stüdyo sesiyle seslendirebilirim.",
  ru: "Привет, я {name}. Я могу озвучить ваши видео, рекламу, курсы и истории естественным студийным голосом.",
  ko: "안녕하세요, 저는 {name}입니다. 영상, 광고, 강의, 이야기를 자연스러운 스튜디오 목소리로 읽어 드릴게요.",
  zh: "你好，我係{name}。我可以用自然嘅錄音室聲音，為你嘅影片、廣告同故事配音。",
  he: "שלום, אני {name}. אני יכול להקריין את הסרטונים, הפרסומות והסיפורים שלכם בקול טבעי באיכות אולפן.",
};

const LIBRARY = RAW.map(([key, name, g, locale]) => ({
  id: 'lib_' + key,
  engineId: 'jsf_default_' + key,
  name,
  gender: g === 'M' ? 'Male' : 'Female',
  language: locale.split('-')[0],
  locale,
  category: 'Library',
  public: true,
  library: true,
  createdAt: '2026-01-01T00:00:00.000Z',
}));

const previewText = (v) => (PREVIEW_TEXT[v.language] || PREVIEW_TEXT.en).replace('{name}', v.name);

module.exports = { LIBRARY, previewText };
